"""sandbox labs

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 10:22:13.766857
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_instances',
    sa.Column('lab_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('reset_of', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('starting', 'running', 'expired', 'stopping', 'stopped', 'failed', name='labstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleaned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.String(length=24), nullable=True),
    sa.Column('failure_code', sa.String(length=48), nullable=True),
    sa.Column('lease_seconds', sa.Integer(), nullable=False),
    sa.Column('canary', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=64), nullable=False),
    sa.Column('network_name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('app_token', sa.String(length=48), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_lab_instances_session_id_learning_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_instances'))
    )
    op.create_index(op.f('ix_lab_instances_session_id'), 'lab_instances', ['session_id'], unique=False)
    op.create_index('ix_lab_instances_status_expires_at', 'lab_instances', ['status', 'expires_at'], unique=False)
    op.create_index('ix_lab_instances_user_id_lab_id', 'lab_instances', ['user_id', 'lab_id'], unique=False)
    op.create_index('uq_lab_instances_live_user', 'lab_instances', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('starting', 'running', 'expired', 'stopping')"), sqlite_where=sa.text("status IN ('starting', 'running', 'expired', 'stopping')"))
    op.create_table('lab_terminal_tickets',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['lab_instances.id'], name=op.f('fk_lab_terminal_tickets_instance_id_lab_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_terminal_tickets')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_lab_terminal_tickets_token_hash'))
    )
    op.create_index(op.f('ix_lab_terminal_tickets_instance_id'), 'lab_terminal_tickets', ['instance_id'], unique=False)
    op.create_table('lab_verifications',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.String(length=48), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('first_passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['lab_instances.id'], name=op.f('fk_lab_verifications_instance_id_lab_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_verifications')),
    sa.UniqueConstraint('instance_id', 'check_id', name='uq_lab_verifications_instance_id_check_id')
    )
    op.create_index(op.f('ix_lab_verifications_instance_id'), 'lab_verifications', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_verifications_instance_id'), table_name='lab_verifications')
    op.drop_table('lab_verifications')
    op.drop_index(op.f('ix_lab_terminal_tickets_instance_id'), table_name='lab_terminal_tickets')
    op.drop_table('lab_terminal_tickets')
    op.drop_index('uq_lab_instances_live_user', table_name='lab_instances', postgresql_where=sa.text("status IN ('starting', 'running', 'expired', 'stopping')"), sqlite_where=sa.text("status IN ('starting', 'running', 'expired', 'stopping')"))
    op.drop_index('ix_lab_instances_user_id_lab_id', table_name='lab_instances')
    op.drop_index('ix_lab_instances_status_expires_at', table_name='lab_instances')
    op.drop_index(op.f('ix_lab_instances_session_id'), table_name='lab_instances')
    op.drop_table('lab_instances')
    # ### end Alembic commands ###
