"""candidate labs and immutable lab versions

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-01 05:43:38.987624
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_candidates',
    sa.Column('family', sa.String(length=48), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'generation_failed', 'spec_only', 'building', 'build_failed', 'validating', 'validation_failed', 'awaiting_review', 'changes_requested', 'rejected', 'approved', name='candidatestatus', native_enum=False, length=32), nullable=False),
    sa.Column('build_status', sa.Enum('pending', 'running', 'passed', 'failed', 'skipped', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'running', 'passed', 'failed', 'skipped', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('security_status', sa.Enum('pending', 'running', 'passed', 'failed', 'skipped', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('stage_detail', sa.String(length=200), nullable=True),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('image_tag', sa.String(length=200), nullable=True),
    sa.Column('image_id', sa.String(length=100), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('validation_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('security_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('guide_run_id', sa.Uuid(), nullable=True),
    sa.Column('generator', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_candidates')),
    sa.UniqueConstraint('family', 'revision', name='uq_lab_candidates_family_revision')
    )
    op.create_index(op.f('ix_lab_candidates_cve_id'), 'lab_candidates', ['cve_id'], unique=False)
    op.create_index('ix_lab_candidates_status', 'lab_candidates', ['status'], unique=False)
    op.create_index('uq_lab_candidates_working_family', 'lab_candidates', ['family'], unique=True, postgresql_where=sa.text("status IN ('generating', 'building', 'validating')"), sqlite_where=sa.text("status IN ('generating', 'building', 'validating')"))
    op.create_table('lab_versions',
    sa.Column('family', sa.String(length=48), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('image_tag', sa.String(length=200), nullable=False),
    sa.Column('image_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('published', 'superseded', 'withdrawn', name='versionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.String(length=64), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_by', sa.String(length=64), nullable=True),
    sa.Column('withdrawn_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_versions')),
    sa.UniqueConstraint('family', 'version', name='uq_lab_versions_family_version'),
    sa.UniqueConstraint('lab_id', name='uq_lab_versions_lab_id')
    )
    op.create_index(op.f('ix_lab_versions_cve_id'), 'lab_versions', ['cve_id'], unique=False)
    op.create_table('lab_reviews',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['lab_candidates.id'], name=op.f('fk_lab_reviews_candidate_id_lab_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_reviews'))
    )
    op.create_index(op.f('ix_lab_reviews_candidate_id'), 'lab_reviews', ['candidate_id'], unique=False)


    # Defence in depth: the application refuses to edit a published version (an ORM guard), and on
    # PostgreSQL the database refuses too, even for a raw UPDATE from a script or a console.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION lab_versions_immutable() RETURNS trigger AS $$
            BEGIN
              IF NEW.family IS DISTINCT FROM OLD.family
                 OR NEW.version IS DISTINCT FROM OLD.version
                 OR NEW.lab_id IS DISTINCT FROM OLD.lab_id
                 OR NEW.cve_id IS DISTINCT FROM OLD.cve_id
                 OR NEW.candidate_id IS DISTINCT FROM OLD.candidate_id
                 OR NEW.spec::text IS DISTINCT FROM OLD.spec::text
                 OR NEW.files::text IS DISTINCT FROM OLD.files::text
                 OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
                 OR NEW.image_tag IS DISTINCT FROM OLD.image_tag
                 OR NEW.image_id IS DISTINCT FROM OLD.image_id
                 OR NEW.published_at IS DISTINCT FROM OLD.published_at
                 OR NEW.published_by IS DISTINCT FROM OLD.published_by THEN
                RAISE EXCEPTION 'published lab versions are immutable';
              END IF;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            "CREATE TRIGGER lab_versions_immutable BEFORE UPDATE ON lab_versions "
            "FOR EACH ROW EXECUTE FUNCTION lab_versions_immutable()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS lab_versions_immutable ON lab_versions")
        op.execute("DROP FUNCTION IF EXISTS lab_versions_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_reviews_candidate_id'), table_name='lab_reviews')
    op.drop_table('lab_reviews')
    op.drop_index(op.f('ix_lab_versions_cve_id'), table_name='lab_versions')
    op.drop_table('lab_versions')
    op.drop_index('uq_lab_candidates_working_family', table_name='lab_candidates', postgresql_where=sa.text("status IN ('generating', 'building', 'validating')"), sqlite_where=sa.text("status IN ('generating', 'building', 'validating')"))
    op.drop_index('ix_lab_candidates_status', table_name='lab_candidates')
    op.drop_index(op.f('ix_lab_candidates_cve_id'), table_name='lab_candidates')
    op.drop_table('lab_candidates')
    # ### end Alembic commands ###
