"""learning sessions

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 09:24:11.688111
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'abandoned', name='learningstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('solution_revealed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('guide_run_id', sa.Uuid(), nullable=True),
    sa.Column('generation_version', sa.String(length=16), nullable=False),
    sa.Column('scoring', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index(op.f('ix_learning_sessions_cve_id'), 'learning_sessions', ['cve_id'], unique=False)
    op.create_index('ix_learning_sessions_user_id_cve_id', 'learning_sessions', ['user_id', 'cve_id'], unique=False)
    op.create_table('learning_attempts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_learning_attempts_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_attempts'))
    )
    op.create_index(op.f('ix_learning_attempts_session_id'), 'learning_attempts', ['session_id'], unique=False)
    op.create_table('learning_hint_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=False),
    sa.Column('hint_number', sa.Integer(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('passage_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_learning_hint_events_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_hint_events'))
    )
    op.create_index(op.f('ix_learning_hint_events_session_id'), 'learning_hint_events', ['session_id'], unique=False)
    op.create_table('learning_task_progress',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('hints_revealed', sa.Integer(), nullable=False),
    sa.Column('best_result', sa.String(length=24), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_learning_task_progress_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_task_progress')),
    sa.UniqueConstraint('session_id', 'task_id', name='uq_learning_task_progress_session_id_task_id')
    )
    op.create_index(op.f('ix_learning_task_progress_session_id'), 'learning_task_progress', ['session_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_tutor_messages_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_messages'))
    )
    op.create_index(op.f('ix_tutor_messages_session_id'), 'tutor_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_messages_session_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_learning_task_progress_session_id'), table_name='learning_task_progress')
    op.drop_table('learning_task_progress')
    op.drop_index(op.f('ix_learning_hint_events_session_id'), table_name='learning_hint_events')
    op.drop_table('learning_hint_events')
    op.drop_index(op.f('ix_learning_attempts_session_id'), table_name='learning_attempts')
    op.drop_table('learning_attempts')
    op.drop_index('ix_learning_sessions_user_id_cve_id', table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_cve_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
